jenkinsci/workflow-cps-global-lib-plugin

src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryTest.java

[JENKINS-34650](https://issues.jenkins-ci.org/browse/JENKINS-34650)
Can reproduce problem but have no idea how to fix. Maybe @kohsuke knows. I tried
```diff
diff --git a/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java b/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
index fdbb0da..cf761cc 100644
--- a/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
+++ b/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java
@@ -5,6 +5,7 @@ import com.cloudbees.groovy.cps.NonCPS;
import com.cloudbees.groovy.cps.SandboxCpsTransformer;
import com.cloudbees.groovy.cps.TransformerConfiguration;
import groovy.lang.Binding;
+import groovy.lang.GroovyClassLoader;
import groovy.lang.GroovyCodeSource;
import groovy.lang.GroovyShell; …
```

[JENKINS-34650] Test for workflowLibs sandbox behavior

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/global/GroovyShellDecoratorImpl.java
src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryTest.java

Acccess to this repository is already restricted to RUN_SCRIPT, there's
no point in further restricting this to sandbox.
This change depends on https://github.com/jenkinsci/workflow-cps-plugin/pull/33

[JENKINS-34650] global lib code should run outside sandbox

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/libs/FolderLibrariesTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/GlobalLibrariesTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryConfigurationTest.java

Picks up https://github.com/jenkinsci/subversion-plugin/pull/168 to restore tests commented out before final merge of #10.
Uses library upload done as part of https://github.com/jenkinsci/subversion-plugin/pull/173.
@reviewbybees esp. @recena

Now that subversion 2.7.1 is released, restoring some commented-out tests

---

src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java

Noticed as part of [JENKINS-38517](https://issues.jenkins-ci.org/browse/JENKINS-38517), though the main thrust of that issue is really something else—that changing **Local module directory** should be discouraged.
@reviewbybees

[JENKINS-38517] Improvements to how libraries are checked out

---

README.md

[JENKINS-40492](https://issues.jenkins-ci.org/browse/JENKINS-40492)
Now that I see how the library name is used, I cannot believe that it was not obvious to me earlier.  Anyway, I added some explanation to make sure that is now absolutely clear.

Explain how the library name is used in @Library()

---

README.md

@jglick @reviewbybees 
When describing classes in a Pipeline Shared Library that have "data" they must be serializable
Fixes https://issues.jenkins-ci.org/browse/JENKINS-38868

Added Serializable and notes

---

src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java

[JENKINS-40408](https://issues.jenkins-ci.org/browse/JENKINS-40408)
Although #18 fixed a bug in library handling, it introduced another one. If there are multiple builds starting at the same time, then they causes a race-condition where the different builds uses the same directory to update the library.

[JENKINS-40408] Fixed concurrency bug introduced in #18

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryDecorator.java

Downstream of https://github.com/jenkinsci/jenkins/pull/1485.
@reviewbybees

Use Functions.printThrowable to provide more legible stack traces in 2.43+

---

src/main/java/org/jenkinsci/plugins/workflow/libs/ClasspathAdder.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryDecorator.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryRecord.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryRetriever.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryStep.java
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/help-includeInChangesets.html
src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryStep/help-changelog.html
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryDecoratorTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java

[JENKINS-41497](https://issues.jenkins-ci.org/browse/JENKINS-41497)
Although it can be useful to see what changes in a shared library could have an impact on a build there are many circumstances that shared library commits should be ignored.
This provides a configuration option to skip adding the changeset of a shared library to a build.
It defaults to including the changeset to match the current behaviour.

JENKINS-41497 make library changesets in a job configurable

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/libs/GlobalLibraries.java
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/cps/global/GrapeTest.java

Like https://github.com/jenkinsci/workflow-cps-plugin/pull/175.
@reviewbybees

[JENKINS-33358] Test against 2.73.x since that includes Groovy 2.4.11

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryMemoryTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/ResourceStepTest.java

Fixes some test regressions detected by PCT.
```
org.junit.ComparisonFailure: expected:<... credentialsId: '', [excludes: '', id: 'id', ignoreOnPushNotifications: true, includes: '*', rawRefSpecs: '+refs/heads/*:refs/remotes/origin/*', remote: 'https://nowhere.net/', remoteName: 'origin']])> but was:<... credentialsId: '', [id: 'id', remote: 'https://nowhere.net/', traits: [[$class: 'BranchDiscoveryTrait'], [$class: 'IgnoreOnPushNotificationTrait']]]])>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.jenkinsci.plugins.workflow.cps.SnippetizerTester.assertRoundTrip(SnippetizerTester.java:95)
at org.jenkinsci.plugins.workflow.libs.LibraryStepTest.configRoundtrip(LibraryStepTest.java:72)
Expected: a string containing "Library …
```

Updates for PCT

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
src/main/java/org/jenkinsci/plugins/workflow/libs/ResourceStep.java
src/main/resources/org/jenkinsci/plugins/workflow/libs/ResourceStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/libs/ResourceStep/help-encoding.html
src/main/resources/org/jenkinsci/plugins/workflow/libs/ResourceStep/help-resource.html
src/main/resources/org/jenkinsci/plugins/workflow/libs/ResourceStep/help.html
src/test/java/org/jenkinsci/plugins/workflow/libs/ResourceStepTest.java

See [JENKINS-52313](https://issues.jenkins-ci.org/browse/JENKINS-52313).
Adds support for a special encoding named "Base64" that can be used for binary files. Useful in tandem with jenkinsci/workflow-basic-steps-plugin#66 to copy binary resource files from shared libraries to the workspace.
~I'd prefer to use Java 8's Base64 API but the plugin is currently building against Java 7 so I am using commons-compress via Jenkins core.~ Baseline has been updated to Java 8 and Jenkins 2.60.3 to use the new Base64 API.
@reviewbybees @jennbriden

[JENKINS-52313] Add encoding argument to ResourceStep and support Base64 encoding

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java

See [JENKINS-53485](https://issues.jenkins-ci.org/browse/JENKINS-53485). 
This wraps access to the InputStream of a file with a try-with-resources block. Prior to recent changes, access to the file contents was done with readToString which does the same.
This change was causing a pretty severe file leak, and this update will wrap the resource in a try-with-resources block like the original implementation to prevent the leak.

[JENKINS-53485] fix to a file leak introduced in libraryResource

---

src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/libs/FailingSCMSource.java
src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java

Similar to jenkinsci/workflow-cps-plugin#147, this adds a retry to the global pipeline library source control-based retrieval, allowing runs to survive temporary network outages when they are attempting to load their libraries.
Testing
=======
1. The output of the new integration test (`retry` - adapted from the test with the same name added in jenkinsci/workflow-cps-plugin#147) looks like the following:
```
=== Starting retry(org.jenkinsci.plugins.workflow.libs.SCMSourceRetrieverTest)
0.077 [id=17]	INFO	o.jvnet.hudson.test.WarExploder#explode: Picking up existing exploded jenkins.war at C:\Users\odagenais\oss\jenkinsci\workflow-cps-global-lib-plugin\target\jenkins-for-test
0.422 [id=17]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:26702/jenkins/
1.251 …
```

feat: retry checkout of global pipeline library

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/cps/global/GrapeTest.java
src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryLocalTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/FolderLibrariesTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/ResourceStepTest.java

I needed a baseline to test https://github.com/jenkinsci/workflow-cps-plugin/pull/211 and this plugin was still using a months-old version predating multiple security fixes.

Testing against workflow-cps 2.67

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java

Downstream of https://github.com/jenkinsci/structs-plugin/pull/43.

CustomDescribableModel can address SCMSourceRetriever.scm.id problem

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java

Same underlying problem as [JENKINS-56682](https://issues.jenkins-ci.org/browse/JENKINS-56682). See https://github.com/jenkinsci/script-security-plugin/pull/259 and https://github.com/jenkinsci/workflow-cps-plugin/pull/297.
This PR updates a bunch of dependencies since I had already had a wip commit to do that locally. More importantly, it adds a new test whose failing stack trace looks like: 
```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use new pkg.Foo
at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectNew(StaticWhitelist.java:271)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onNewInstance(SandboxInterceptor.java:174)
at …
```

[JENKINS-56682] Reproduce and fix issue using types from shared libraries in Script initializers

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/global/GrapeTest.java

In #65, we discovered that `GrapeTest.var` breaks with new versions of jenkins-test-harness. See https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/65#issuecomment-505091612 for details. This PR fixes the issue by switching from `commons-math3` to `commons-primitives`, which was already being used in other tests here.

Make GrapeTest.var work with new versions of jenkins-test-harness

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryRetriever.java
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java

[JENKINS-43802](https://issues.jenkins-ci.org/browse/JENKINS-43802)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/65.

[JENKINS-43802] No context available for credentials from SCMSource.retrieve(String, TaskListener)

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryDecorator.java

In #31, a call to `Functions.printThrowable` was added with a TODO comment to switch to `Functions.printStackTrace` when the baseline was bumped to 2.43+. The baseline is now 2.138.4, so this TODO can be completed.
This code doesn't appear to have any test coverage, but I feel confident about the change based on the similar logic that is present in `SCMSourceRetriever` and the testing I did for a similar change in jenkinsci/workflow-basic-steps-plugin#91.

Use Functions.printStackTrace

---

src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryTest.java

While looking at the test suite for this plugin, I noticed the CpsFlowDefinitions in the tests don't consistently use the script security sandbox. Always using the script security sandbox makes the tests consistent with each other, and it's also a more realistic environment given that the script security sandbox should always be enabled in production.
I In this change, I replaced any usages of the deprecated single-argument constructor for `CpsFlowDefinition` with usages of the non-deprecated two-argument constructor, passing in `true` as the second argument in order to enable the script security sandbox.

Consistently use sandbox for CpsFlowDefinitions

---

src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java

Regression test to detect problems like https://github.com/jenkinsci/workflow-cps-global-lib-plugin/commit/3a6e48b5d8090fba3cfb88491a2fb986e95fffa4.
While this does its job in making sure specific implementations does not get legacy accidentally, it provides no forward-looking guarantee that `SCMSource`'s API and `SCMSourceRetriever.DescriptorImpl#getSCMDescriptors()` stays in sync. IOW, when someone changes API of `SCMSource` and forgets to update `#getSCMDescriptors()`, they are very likely to forget to update this test (that would detect that) as well. Which is how [JENKINS-58964](https://issues.jenkins-ci.org/browse/JENKINS-58964) originated.
Slightly aggressive measure I can think of is to assert this exact API of `SCMSource` in the test so _every_ change to that API would cause it …

JENKINS-58964 : Regression tests to ensure important impls are modern

---

pom.xml

Amends #71. Noticed via https://github.com/jenkinsci/maven-hpi-plugin/pull/130. Without this, `apache-httpcomponents-client-4-api` is in `compile` scope (despite being only here due to `workflow-basic-steps`, a `test`-scoped dep), and thus various things like `http-core` are as well, so `hpi:hpi` gets confused (since the direct dep `workflow-basic-steps` is not in its listed of recognized plugin dependencies) and bundles them, bloating the archive.

[JENKINS-58771] Do not bundle JARs from apache-httpcomponents-client-4-api

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/cps/global/GrapeTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/FolderLibrariesTest.java

Fixes issues when running this plugin in the PCT as seen in https://github.com/jenkinsci/bom/pull/189.
Previously, the use of `@Grab` did not cause the scripts in these tests to fail until runtime, but after the fixes for SECURITY-1713, the scripts now fail at compile time with a different error message.

Adapt tests affected by fixes for SECURITY-1713

---

pom.xml

Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 3.50 to 3.54.
See [the changelog](https://github.com/jenkinsci/plugin-pom/releases) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-3.50...plugin-3.54).

Bump plugin parent POM

---

src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/cps/global/CompilationErrorsExceptionTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java

#83 brought to my attention that some users are putting test code for their shared libraries in `src/test`, mostly when using https://github.com/jenkinsci/JenkinsPipelineUnit, which is not a good idea, since it means that the test code is available to Pipelines using the library. To help users who might have made this mistake accidentally (e.g. `pipeline-library` before https://github.com/jenkins-infra/pipeline-library/pull/138), this PR makes it so that `src/test` is specifically excluded when a shared library is checked out.
In case users were actually using a a package named `test` in their shared library, there is a system property that can be set as an escape hatch to restore the previous behavior.

Exclude src/test/ from shared libraries by default

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryStep.java

See: https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/93#pullrequestreview-391129809
@jglick @dwnusbaum @bitwiseman

Remove commons-lang3

---

src/test/java/org/jenkinsci/plugins/workflow/libs/GlobalLibrariesTest.java

This test fails on the latest LTS (2.222.1) picked up in https://github.com/jenkinsci/bom/pull/214
Most likely due to: https://github.com/jenkinsci/jenkins/pull/4365
The test case appears to be invalid now so have removed the RUN_SCRIPTS testing
cc @dwnusbaum @bitwiseman @jglick

Adjust GlobalLibraries#configRoundTrip test for latest LTS

---

Jenkinsfile
pom.xml

According to http://stats.jenkins.io/pluginversions/workflow-cps-global-lib.html
98% of users on the latest version are on this version or above
88% on the previous version are on this version or above
97% on the previous version are on one of the previous LTS releases in
this line and could likely easily upgrade
When testing https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/94 I was unable to test it interactively due to conflicts in plugin loading, ssh-credentials and git both failed to load. With these changes I was able to test it
Can lower the core and use 3.x plugin-pom if maintainers prefer
cc @dwnusbaum @bitwiseman

Introduce bom and bump minimum required version

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibrariesAction.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryStep.java

Should solve the cases of [JENKINS-41037](https://issues.jenkins-ci.org/browse/JENKINS-41037) associated with the `libraries` step, which is most of them. Alternative to https://github.com/x-stream/xstream/pull/222. Not tested (do not know how to reproduce problem).
Note that `CopyOnWriteList` is an alternative fix, for cases where it would be awkward to make the collection immutable, but in this case there is only one piece of code that was ever mutating this list so it is most straightforward to fix that.

[JENKINS-41037] Prevent ConcurrentModificationException serializing LibrariesAction.libraries

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java

The git snippet test will fail when the git plugin dependency is updated to git plugin 4.6.0.  This pull request shows one way to fix the test.
Recent releases of the git plugin require 2.222.4 as their minimum Jenkins version.  Jenkins 2.235.1 is the version recommended by https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/
[Git plugin 4.6.0](https://github.com/jenkinsci/git-plugin/releases/tag/git-4.6.0) removed the undocumented submodule configurator experiment so that the pipeline syntax snippet generator no longer includes `doGenerateSubmoduleConfigurations` or `submoduleCfg`.  They are accepted as arguments but any values assigned to them are ignored.
The test could have been adapted to run with both older and newer versions of the git plugin, but it …

Fix git snippet test

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibrariesAction.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryRecord.java

This PR exposes data about shared libraries used by a build through the Jenkins REST API. The information was already being stored in `LibrariesAction` and `LibraryRecord`, it was just not exposed to the API. Somewhat similar to #102, which I also think is a good idea. 
I did not add any tests in this PR that use the API, but I could do so if desired.

Expose LibrariesAction and LibraryRecord to Jenkins' REST API

---

src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java

See [JENKINS-66629](https://issues.jenkins.io/browse/JENKINS-66629). `SCMSourceRetriever` creates a `@libs` workspace for retrieving the shared library before copying it into the build directory. While old build directories are eventually discarded based on the global build discarder configuration, these `@libs` workspaces are leaked when the job is renamed or deleted.
When a job's location changes or is deleted, delete the old (now leaked) `@libs` workspace. If the job's location changed, a new `@libs` workspace will be created at the new location the next time the job runs.
As suggested in [jenkinsci/workflow-cps-global-lib-plugin#110 (comment)](https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/110#issuecomment-840695808), implement `ItemListener#onDeleted` so …

[JENKINS-66629] `SCMSourceRetriever` leaks `@libs` workspaces

---

src/test/java/org/jenkinsci/plugins/workflow/libs/ResourceStepTest.java

Java 8 includes a built-in Base64 encoder, so there is no reason to depend on a third-party library. Using the built-in Java Platform functionality simplifies maintenance.

Drop dependency on Commons Codec

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfigurationTest.java

- [JENKINS-66045](https://issues.jenkins.io/browse/JENKINS-66045) test for NPE if exclusions are empty
- [JENKINS-66045](https://issues.jenkins.io/browse/JENKINS-66045) Fix NPE checking version exclusion

[JENKINS-66045] Fix NPE in cache exclusions

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
src/test/java/org/jenkinsci/plugins/workflow/libs/ResourceStepTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java

The tests for security fixes for https://www.jenkins.io/security/advisory/2022-02-15/ fail against recent version of Git plugin due to https://github.com/jenkinsci/git-plugin/pull/1207, and also fail when running on Windows due to a difference in the behavior.
The fix itself also did not allow `JENKINS_HOME` to be a symlink, because it compared a canonical path to an absolute path.

Fix recent security fixes if JENKINS_HOME is a symlink and update tests for compatibility with Windows and Git plugin 4.10.3

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration.java
src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration/help-excludedVersionsStr.html
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfigurationTest.java

Converting the library cache code to be a substring search vice explicit string.  This enables blanket exemptions for things like feature branches without breaking current functionality. This is required to enable caching for branches like master and exclude others without having to know the full name as a feature branch would be dynamic.
All tests run and caching works as expected with change.  Unfortunately I cannot upload screenshots due to work requirements. I validated all build tests worked as well.

convert library cache exclude to substring search

---

src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryMemoryTest.java

When testing JENKINS-45047 in `jenkinsci/bom`, I noticed this failure. The failure is probably already occurring in PCT, but due to bugs in PCT we are probably just not seeing it.
Clone `workflow-cps-global-lib` and add the latest version of `support-core` as a test-scoped dependency, for example with
```xml
diff --git a/pom.xml b/pom.xml
index 3eb584a..9bceb16 100644
--- a/pom.xml
+++ b/pom.xml
@@ -63,7 +63,7 @@
</pluginRepositories>
<properties>
<changelist>999999-SNAPSHOT</changelist>
-        <jenkins.version>2.303.1</jenkins.version>
+        <jenkins.version>2.332.1</jenkins.version>
<java.level>8</java.level>
<gitHubRepo>jenkinsci/${project.artifactId}-plugin</gitHubRepo>
</properties>
@@ -71,8 +71,8 @@
<dependencies>
<dependency>
<groupId>io.jenkins.tools.bom</groupId>
- …
```

[JENKINS-68375] `LibraryMemoryTest#loaderReleased` fails on Java 17 when `support-core` is present

---

src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingCleanup.java
src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration.java
src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration/config.jelly
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingCleanupTest.java
src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfigurationTest.java

The security fixes related to the cache feature in https://github.com/jenkinsci/workflow-cps-global-lib-plugin/commit/ace0de3c2d691662021ea10306eeb407da6b6365 broke `LibraryCachingCleanup` (cleans up unused cache directories) and `LibraryCachingConfiguration.doClearCache` (allows admins to manually delete all cached versions of a specific library). This went unnoticed because neither piece of functionality had any test coverage.
This PR fixes the issues with library cache deletion after SECURITY-2586 and adds relevant test coverage.

Fix library cache deletion after SECURITY-2586

---

src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryLocalTest.java

Simpler alternative to #169. The signatures of the methods being used in this test changed in https://github.com/jenkinsci/workflow-cps-plugin/commit/6bd4e8bf837ba1df4394efdd003c70bb1b9ac33f, which causes this plugin's tests to fail to compile in the PCT. The assertions are not particularly interesting in this case since the sandbox is being used (see https://github.com/jenkinsci/workflow-cps-plugin/blob/8732e3150b97bd4213401814ba72925ebfa86e0d/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java#L163), so I think it is fine to just delete them to avoid needing to update the minimum Jenkins just to fix this test.

Fix test compilation errors caused by signature changes in SECURITY-2450

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/cps/global/GroovyShellDecoratorImpl.java
src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariableList.java
src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariableRepoListener.java
src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepository.java
src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibSshRepository.java
src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryTest.java

Without dropping compatibility with Guice 6 (currently delivered by Jenkins core), add support for Guice 7.

Forward compatibility with Guice 7
