jenkinsci/workflow-cps-global-lib-plugin

- src/main/java/org/jenkinsci/plugins/workflow/cps/global/GroovyShellDecoratorImpl.java
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariable.java
- src/test/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryTest.java
[JENKINS-34517](https://issues.jenkins-ci.org/browse/JENKINS-34517)
@reviewbybees
> [JENKINS-34517] Global variables caused ClassNotFoundException’s when resuming builds

- src/main/java/org/jenkinsci/plugins/workflow/cps/global/GlobalRepoHookListener.java
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariableRepoListener.java
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepository.java
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepositoryListener.java
[JENKINS-34008](https://issues.jenkins-ci.org/browse/JENKINS-34008)
Yup, it's back but this time against the new repo. =)
Existing rebuild test validates this change.
cc @reviewbybees
> [JENKINS-34008] Add a hook listener for the global library

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/GrapeHack.java
- src/test/java/org/jenkinsci/plugins/workflow/cps/global/GrapeTest.java
[JENKINS-26192](https://issues.jenkins-ci.org/browse/JENKINS-26192)
@reviewbybees
> [JENKINS-26192] Support @Grab from global libs

- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
Incidental to the real issue in [JENKINS-38048](https://issues.jenkins-ci.org/browse/JENKINS-38048) but should be fixed nonetheless.
@reviewbybees
> [JENKINS-38048] Deleting obsolete query parameter

- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
- src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/config.jelly
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryConfigurationTest.java
[JENKINS-38550](https://issues.jenkins-ci.org/browse/JENKINS-38550)
@reviewbybees
> [JENKINS-38550] Hide currently inapplicable LibraryRetrieverDescriptor’s

- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
- src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMRetriever/config.jelly
- src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMRetriever/help.html
- src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever/config.jelly
- src/main/resources/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever/help.html
See [JENKINS-38712](https://issues.jenkins-ci.org/browse/JENKINS-38712) for why I did not do this to begin with: there are drawbacks to the new control.
@reviewbybees
> [JENKINS-38712] Avoid deep indentation

- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
Fails without fix from https://github.com/jenkinsci/workflow-cps-plugin/pull/83.
@reviewbybees
> Memory leak test

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
> Running memory tests

- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetrieverTest.java
Extends #25 with a test.
@reviewbybees
> [JENKINS-40408] Workspace lease race condition

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/RestartTest.java
Demonstrates effectiveness of https://github.com/cloudbees/groovy-cps/pull/46. Downstream of https://github.com/jenkinsci/workflow-cps-plugin/issues/100.
@reviewbybees
> [JENKINS-39719] Integration test

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariable.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryStep.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/FolderLibrariesTest.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/GlobalLibrariesTest.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java
> Added a Jenkinsfile, and fixed some buglets on Windows

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/FolderLibrariesTest.java
Integration test for https://github.com/jenkinsci/workflow-cps-plugin/pull/120.
@reviewbybees
> [JENKINS-43019] Suppressing GroovyClassLoader.InnerLoader

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
Downstream of https://github.com/jenkinsci/plugin-pom/pull/67.
@reviewbybees
> [JENKINS-41631] Demonstration of POM update

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/SCMRetrieverTest.java
Compare to #37. [This trick](https://stackoverflow.com/a/49112612/12916) apparently works, so…we ought to have a test verifying that it keeps working.
@reviewbybees @schnatterer
> Demonstrating that retriever: legacySCM(scm) can be used to self-test libraries

- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java
I have got this test written desperately trying to reproduce an unrelated problem.
> Test adding tool from pipeline library

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/SCMRetrieverTest.java
See jenkinsci/jenkins-test-harness#113. Filing now to test the upstream PR and so that I actually remember that the tests should be unignored.
> Pick up various updates to shorten file names on Windows

- pom.xml
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariable.java
- src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepository.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/GlobalLibraries.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryStep.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
This is based on the analysis https://ci.jenkins.io/job/Infra/job/deprecated-usage-in-plugins/job/master/566/artifact/output/usage-by-plugin.html.
> Avoid deprecated api usage

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryMemoryTest.java
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/289.
> [JENKINS-50223] Memory leak integration testing

- pom.xml
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryDecoratorTest.java
Integration test for https://github.com/jenkinsci/workflow-cps-plugin/pull/284.
> [JENKINS-57085] Bad stack trace deserialization when URLs used as filenames

- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryConfigurationTest.java
See [JENKINS-59527](https://issues.jenkins-ci.org/browse/JENKINS-59527).
> [JENKINS-59527] Trim white space name and version

- CHANGELOG.md
I am planning on releasing the plugin today.
> Add changelog entries for 2.15 and 2.16

- Jenkinsfile
- pom.xml
Same as #95 but just here to get CI.
> Use bom bump core

- CHANGELOG.md
- Jenkinsfile
I am planning on releasing the plugin today.
> Add release notes for 2.17

- pom.xml
Fixes PCT on Java 11
https://github.com/jenkinsci/bom/pull/401
> Bump subversion plugin dep

- CHANGELOG.md
Update changelog for 2.19. Planning to release today
> update CHANGELOG for 2.19

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- CHANGELOG.md
- README.md
> Enable release-drafter

- src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration/help-cachingConfiguration.html
Replace references of "master" to "controller" for inclusive naming initiative
Signed-off-by: Darin Pope <darin@planetpope.com>
> hacktoberfest - update master to controller

- src/main/java/org/jenkinsci/plugins/workflow/cps/global/UserDefinedGlobalVariable.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/ClasspathAdder.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/FolderLibraries.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/GlobalLibraries.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryConfiguration.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryResolver.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryRetriever.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryStep.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/ResourceStep.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMRetriever.java
- src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/FailingSCMSource.java
- src/test/java/org/jenkinsci/plugins/workflow/libs/FailingSCMSourceDuringFetch.java
> EOL JSR 305

- src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepository.java
Rather than "master" use "controller"
~~Ensure you have provided tests - that demonstrate the feature works or fixes the issue~~
> Make a comment more inclusive

- pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
> Remove unused Ivy dependency
